general_cfg:
  algo_name: PER_DQN
  device: cpu
  env_name: gym
  mode: train
  mp_backend: mp # 多线程框架，ray或者mp(multiprocessing)，默认mp
  n_workers: 2 # number of workers for parallel training
  load_checkpoint: false
  load_path: Train_CartPole-v1_PER_DQN
  max_steps: 200
  save_fig: true
  seed: 1
  show_fig: false
  test_eps: 10
  train_eps: 200
algo_cfg:
  value_layers:
    - layer_type: linear
      layer_dim: ['n_states',256]
      activation: relu
    - layer_type: linear
      layer_dim: [256,256]
      activation: relu
    - layer_type: linear
      layer_dim: [256,'n_actions']
      activation: none
  batch_size: 64
  buffer_size: 100000
  per_alpha: 0.6
  per_beta: 0.4
  per_beta_annealing: 0.001
  per_epsilon: 0.01
  epsilon_decay: 500
  epsilon_end: 0.01
  epsilon_start: 0.95
  gamma: 0.99
  lr: 0.0001
  target_update: 4
