general_cfg:
  algo_name: NoisyDQN
  device: cpu
  env_name: gym
  mode: test
  mp_backend: mp # 多线程框架，ray或者mp(multiprocessing)，默认mp
  n_workers: 1 # number of workers for parallel training
  load_checkpoint: true
  load_path: Train_CartPole-v1_NoisyDQN_mp_20230413-220639
  max_steps: 200
  save_fig: true
  seed: 1
  show_fig: false
  test_eps: 10
  train_eps: 200
algo_cfg:
  hidden_dim: 256
  batch_size: 64
  buffer_size: 100000
  epsilon_decay: 500
  epsilon_end: 0.01
  epsilon_start: 0.95
  gamma: 0.95
  lr: 0.0001
  target_update: 4
env_cfg:
  id: CartPole-v1
  new_step_api: true
  render_mode: null
