general_cfg:
  algo_name: DuelingDQN
  device: cpu
  env_name: CartPole-v1
  mode: train
  mp_backend: ray # 多线程框架，ray或者mp(multiprocessing)，默认mp
  n_workers: 2 # number of workers for parallel training
  load_checkpoint: false
  load_path: Train_CartPole-v1_DQN_20221026-054757
  max_steps: 200
  save_fig: true
  seed: 1
  show_fig: false
  test_eps: 10
  train_eps: 400
algo_cfg:
  hidden_dim: 256
  batch_size: 64
  buffer_size: 100000
  epsilon_decay: 500
  epsilon_end: 0.01
  epsilon_start: 0.95
  gamma: 0.99
  lr: 0.0001
  target_update: 4
