general_cfg:
  algo_name: Sarsa
  device: cpu
  env_name: CliffWalking-v0
  wrapper: envs.wrappers.CliffWalkingWapper
  mode: train
  load_checkpoint: false
  load_path: Train_CartPole-v1_DQN_20221026-054757
  max_steps: 100
  save_fig: true
  seed: 1
  show_fig: false
  test_eps: 10
  train_eps: 400
algo_cfg:
  exploration_type: e-greedy # softmax, ucb
  epsilon_decay: 300
  epsilon_end: 0.01
  epsilon_start: 0.95
  gamma: 0.99
  lr: 0.1
